---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      ignore_errors: yes

    - name: get default users
      shell: ls -I ansible /home
      register: get_user

    - set_fact:
        default_user: "{{ get_user.stdout | from_yaml }}"

    - name: print default user
      debug:
        var: default_user
    
    - name: print MAC address
      debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/dns.yml
    - include: tasks/gnome.yml

  handlers:
    - include: handlers/main.yml
