- name: copy the @reboot script
  copy: "src=files/reboot.sh dest=/home/ansible/cron/reboot.sh owner=ansible group=ansible mode=700"

- name: remove old cron job
  cron: user="ansible" name="EducaTM OS provision" state=absent

- name: install cron job (ansible-pull)
  cron: user="ansible" special_time="reboot" name="EducaTM OS provision" job="/home/ansible/cron/reboot.sh"
