- name: Install flatpak apps
  flatpak: 
    name: "{{item}}"
    state: present
    method: system
  with_items:
    - com.anydesk.Anydesk
    - us.zoom.Zoom

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: yes