- name: Copy wallpaper file
  copy:
    src: files/wallpaper.jpg
    dest: "/home/{{ default_user }}/Pictures/wallpaper.jpg"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0600'

- name: Set wallpaper
  command: "xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitorVirtual-0/workspace0/last-image --set /home/{{ default_user }}/Pictures/wallpaper.jpg"
  become: yes
  become_user: "{{ default_user }}"